%% 实验四 · 用脚本搭出接收模型 v22_receive.slx
%
%  为什么用脚本建模而不是手工连线：本模型要和 v22_demod.m 这个黄金参考
%  逐步对应，脚本建出来可复现、可 diff、改参数不用重新拖线。
%  产物 v22_receive.slx 入库，之后正常用 Ctrl+B 生成代码。
%
%  模型结构（一帧 = 960 样本 @9600Hz = 100ms = 60 个符号）：
%
%    Inport AudioIn (int16[960])
%      -> Gain 1/32768 + 转 double      归一化
%      -> MATLAB Function  ddc          下变频（相位累加器跨帧连续）
%      -> Discrete FIR Filter           RRC 匹配滤波（129 抽头）
%      -> MATLAB Function  symrx        定时 + AGC + 判决引导载波环
%      -> Outport symOut (double[120])  60 个符号的 I,Q 交替
%
%  分层同现有三个实验：板上只出「每符号一个判决量」，帧同步/解扰/HDLC/
%  还原图片全在 PC 端。不同的是本实验出的是复符号而不是标量——PC 端因此
%  能画星座图，这是 16-QAM 实验必要的诊断手段。

mdl = 'v22_receive';
P   = v22_params(2400);
FRAME_SYMS = 60;
FRAME_LEN  = FRAME_SYMS * P.sps;        % 960
OUT_LEN    = FRAME_SYMS * 2;            % 120 (I,Q 交替)

if bdIsLoaded(mdl), close_system(mdl, 0); end
if isfile([mdl '.slx']), delete([mdl '.slx']); end
new_system(mdl);
open_system(mdl);

add_block('simulink/Sources/In1', [mdl '/AudioIn']);
set_param([mdl '/AudioIn'], 'OutDataTypeStr','int16', ...
          'PortDimensions', num2str(FRAME_LEN), 'Position','[30 100 60 114]');

add_block('simulink/Signal Attributes/Data Type Conversion', [mdl '/ToDouble']);
set_param([mdl '/ToDouble'], 'OutDataTypeStr','double','Position','[110 95 160 119]');

add_block('simulink/Math Operations/Gain', [mdl '/Normalize']);
set_param([mdl '/Normalize'], 'Gain','1/32768','Position','[195 95 225 119]');

add_block('simulink/User-Defined Functions/MATLAB Function', [mdl '/ddc']);
set_param([mdl '/ddc'], 'Position','[270 90 340 124]');

add_block('simulink/Discrete/Discrete FIR Filter', [mdl '/RRC']);
% InputProcessing 必须设成 frame based：默认的 sample based 会把 960 元素的
% 输入向量当成 960 个独立通道，各自维护一套滤波器状态、沿帧方向根本不滤波。
% 建模时踩过这个坑——星座散开但 AGC 正常，就是这个症状。
set_param([mdl '/RRC'], 'Coefficients', ...
          sprintf('rcosdesign(%g,%d,%d,''sqrt'')', P.beta, P.span, P.sps), ...
          'InputProcessing','Columns as channels (frame based)', ...
          'Position','[385 90 455 124]');

add_block('simulink/User-Defined Functions/MATLAB Function', [mdl '/symrx']);
set_param([mdl '/symrx'], 'Position','[500 90 570 124]');

add_block('simulink/Sinks/Out1', [mdl '/symOut']);
set_param([mdl '/symOut'], 'Position','[615 100 645 114]');

add_line(mdl,'AudioIn/1','ToDouble/1');
add_line(mdl,'ToDouble/1','Normalize/1');
add_line(mdl,'Normalize/1','ddc/1');
add_line(mdl,'ddc/1','RRC/1');
add_line(mdl,'RRC/1','symrx/1');
add_line(mdl,'symrx/1','symOut/1');

%% ---- 两个 MATLAB Function 的代码 ----
% 下变频：相位累加器必须跨帧连续，否则每帧开头相位跳变，载波环永远锁不住。
ddcCode = sprintf([ ...
'function y = ddc(x)\n' ...
'%%#codegen\n' ...
'%% 下变频到基带。ph 是 persistent 的——跨帧连续是关键，\n' ...
'%% 每帧重置会让载波相位每 100ms 跳一次，环路锁不住。\n' ...
'persistent ph\n' ...
'if isempty(ph), ph = 0; end\n' ...
'N = int32(%d);\n' ...
'dph = 2*pi*%g/%g;\n' ...
'y = complex(zeros(N,1));\n' ...
'for k = 1:N\n' ...
'    y(k) = x(k) * complex(cos(-ph), sin(-ph)) * 2;\n' ...
'    ph = ph + dph;\n' ...
'    if ph > 2*pi, ph = ph - 2*pi; end\n' ...
'end\n'], FRAME_LEN, P.fc, P.fs);

% 符号级：定时相位用「每帧对 16 个相位算能量、平滑后取最大」——比 Gardner 环
% 好讲也好生成代码，且本实验收发同源、漂移极小（实测一整个突发内 <1/16 符号）。
symCode = sprintf([ ...
'function y = symrx(x)\n' ...
'%%#codegen\n' ...
'%% 输入 960 点匹配滤波输出，输出 60 个符号的 I,Q 交替共 120 个 double。\n' ...
'%% 三件事：定时相位选择、AGC、判决引导二阶载波环。\n' ...
'%% 与 v22_demod.m 逐步对应，改算法先改那边、仿真验过再改这里。\n' ...
'persistent eAcc agc th integ active\n' ...
'SQUELCH = 1e-3;\n' ...
'SPS = int32(%d);  NS = int32(%d);\n' ...
'if isempty(eAcc)\n' ...
'    eAcc = zeros(%d,1); agc = 0; th = 0; integ = 0; active = 0;\n' ...
'end\n' ...
'%% --- 定时：对每个候选相位累计能量，一阶平滑后取最大 ---\n' ...
'for p = 1:SPS\n' ...
'    s = 0;\n' ...
'    for k = 1:NS\n' ...
'        s = s + abs(x(int32(p) + (k-1)*SPS));\n' ...
'    end\n' ...
'    eAcc(p) = 0.9*eAcc(p) + 0.1*s;\n' ...
'end\n' ...
'bo = int32(1); bv = eAcc(1);\n' ...
'for p = 2:SPS\n' ...
'    if eAcc(p) > bv, bv = eAcc(p); bo = int32(p); end\n' ...
'end\n' ...
'%% --- AGC + 静噪 ---\n' ...
'%% 逐帧归一化而不是慢跟踪：慢跟踪在静音帧会把 agc 顶到天上（m 极小时\n' ...
'%% agc=REF/m 发散），而每帧只回落 10%%，整个突发都救不回来——实测过。\n' ...
'%% 低于门限就判为无载波，输出 0 并复位环路，相当于真实 modem 的载波检测。\n' ...
'm = 0;\n' ...
'for k = 1:NS\n' ...
'    m = m + abs(x(bo + (k-1)*SPS));\n' ...
'end\n' ...
'm = m / double(NS);\n' ...
'if m > SQUELCH\n' ...
'    agc = %g/m;\n' ...
'    if active == 0\n' ...
'        th = 0; integ = 0;\n' ...        %% 刚检到载波，环路从零起步
'    end\n' ...
'    active = 1;\n' ...
'else\n' ...
'    agc = 0; active = 0; th = 0; integ = 0;\n' ...
'end\n' ...
'%% --- 判决引导二阶载波环 ---\n' ...
'y = zeros(%d,1);\n' ...
'for k = 1:NS\n' ...
'    z = x(bo + (k-1)*SPS) * agc * complex(cos(-th), sin(-th));\n' ...
'    re = real(z); im = imag(z);\n' ...
'    if re >= 0 && im >= 0, qi = 0; elseif re < 0 && im >= 0, qi = 1;\n' ...
'    elseif re < 0 && im < 0, qi = 2; else, qi = 3; end\n' ...
'    a = -pi/2*double(qi);\n' ...
'    p1 = z * complex(cos(a), sin(a));\n' ...
'    %% 象限内最近点（16-QAM 的 4 个点；QPSK 时前 1 个即可）\n' ...
'    bi = 1; bd = inf;\n' ...
'    for q = 1:4\n' ...
'        dd = abs(p1 - QREF(q));\n' ...
'        if dd < bd, bd = dd; bi = q; end\n' ...
'    end\n' ...
'    dh = QREF(bi) * complex(cos(-a), sin(-a));\n' ...
'    pe = angle(z * conj(dh));\n' ...
'    integ = integ + %g*pe;\n' ...
'    th = th + %g*pe + integ;\n' ...
'    y(2*k-1) = real(z);\n' ...
'    y(2*k)   = imag(z);\n' ...
'end\n' ...
'\n' ...
'function v = QREF(i)\n' ...
'%%#codegen\n' ...
'c = [1+1i, 3+1i, 1+3i, 3+3i];\n' ...
'v = c(i);\n'], ...
P.sps, FRAME_SYMS, P.sps, mean(abs(P.inQ)), OUT_LEN, 2e-4, 0.05);

S = sfroot;
c1 = S.find('-isa','Stateflow.EMChart','Path',[mdl '/ddc']);    c1.Script = ddcCode;
c2 = S.find('-isa','Stateflow.EMChart','Path',[mdl '/symrx']);  c2.Script = symCode;

%% ---- 配置：与前三个实验完全一致 ----
set_param(mdl,'SolverType','Fixed-step','FixedStep','0.1','StopTime','inf');
set_param(mdl,'SystemTargetFile','ert.tlc');
set_param(mdl,'HardwareBoard','None');
set_param(mdl,'ProdHWDeviceType','ARM Compatible->ARM Cortex-A (64-bit)');
set_param(mdl,'GenCodeOnly','on');
set_param(mdl,'MatFileLogging','off');
set_param(mdl,'Toolchain','Automatically locate an installed toolchain');
set_param(mdl,'RootIOFormat','Part of model data structure');   % 见 Q13b
% 不生成示例主程序：ert_main.c 里有 main()，会和本工程手写的 src/main.c
% 撞符号（/usr/bin/ld: multiple definition of `main'）。前三个实验的生成
% 代码里也没有这个文件。
set_param(mdl,'GenerateSampleERTMain','off');

save_system(mdl);
fprintf('已建出 %s.slx（%d 样本/帧 -> %d 个输出）\n', mdl, FRAME_LEN, OUT_LEN);
